CREATE OR REPLACE TABLE TB_MEMBER(
    MEMBER_SEQ                    INT AUTO_INCREMENT PRIMARY KEY
  , MEMBER_ID                     VARCHAR(20)
  , MEMBER_PASSWORD               VARCHAR(60)
  , MEMBER_NAME                   VARCHAR(20)
  , MEMBER_EMAIL                  VARCHAR(50)
  , MEMBER_REG_ID                 VARCHAR(20) DEFAULT MEMBER_ID
  , MEMBER_UPD_ID                 VARCHAR(20)
  , MEMBER_REG_DATETIME DATETIME  DEFAULT NOW()
  , MEMBER_UPD_DATETIME DATETIME  ON UPDATE NOW()
  , ACTIVE                        CHAR(1) DEFAULT 'Y'
)
;

CREATE OR REPLACE TABLE TB_WORK_LOG (
    SEQ           INT AUTO_INCREMENT PRIMARY KEY
  , TITLE         VARCHAR(50)
  , CONTENT       VARCHAR(10000)
  , REG_DATETIME  DATETIME
  , REG_ID        VARCHAR(20)
  , UPD_DATETIME  DATETIME
  , UPD_ID        VARCHAR(20)
  , ACTIVE        CHAR(1)
);