CREATE OR REPLACE TABLE TB_MEMBER(
    MEMBER_SEQ                    INT PRIMARY KEY AUTO_INCREMENT
  , MEMBER_ID                     VARCHAR(20)
  , MEMBER_PASSWORD               VARCHAR(60)
  , MEMBER_NAME                   VARCHAR(20)
  , MEMBER_EMAIL                  VARCHAR(50)
  , MEMBER_REG_ID                 VARCHAR(20) DEFAULT MEMBER_ID
  , MEMBER_UPD_ID                 VARCHAR(20)
  , MEMBER_REG_DATETIME DATETIME  DEFAULT NOW()
  , MEMBER_UPD_DATETIME DATETIME  ON UPDATE NOW()
  , ACTIVE                        CHAR(1) DEFAULT 'Y'
)
;

